name: serveme
description: Backend server framework designed for a quick development of modular WebSocket based server applications with MongoDB integration.
version: 1.2.2
homepage: https://github.com/sourcecaster/serveme
repository: https://github.com/sourcecaster/serveme
issue_tracker: https://github.com/sourcecaster/serveme/issues
documentation: https://github.com/sourcecaster/serveme
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  mongo_dart: ^0.9.1
  yaml: ^3.1.0
  connectme: ^2.2.0
  packme: ^2.0.1
dev_dependencies:
  test: ^1.24.6