name: serveme
description: Framework for console server applications
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  mongo_dart: ^0.7.0+2
  yaml: ^3.1.0
  connectme: ^1.1.1
  packme: ^1.1.5
